import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import '../styles/globals.css'
import styles from '../styles/Home.module.css'
import { NextUIProvider } from '@nextui-org/react';
// import { createTheme } from "@nextui-org/react"

// const darkTheme = createTheme({
//   type: 'dark',
// });

function MyApp({ Component, pageProps }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>LGBT cast</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <div>
          <Link href="/">
              <a>List</a>
          </Link>
          {" "}
          <Link href="/chart">
              <a>Chart</a>
          </Link>
        </div>
        
      </header>

      <main className={styles.main}>
        <NextUIProvider>
          <Component {...pageProps} />
        </NextUIProvider>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default MyApp
